src/main/resources/templates/fragments/javascript.html
src/main/resources/templates/index.html
src/main/resources/templates/maintainance.html
src/main/resources/templates/ss.html

DEV-774 Use https for links in web ui

---

src/main/java/sg/ncl/MainController.java

DEV-790 Fixed signup form repopulation for other redirections

---

src/main/resources/static/js/main.js
src/main/resources/templates/experiments.html

1. Show Nodes Status link at the bottom-right position
2. For experiment “Start”, “Stop” and “Remove” button, add a confirmation dialog

DEV-930 improve ui for experiment page

---

src/main/resources/templates/experiment_page_create_experiment.html

5. Create Experiment
Change “Description” to text field (long text)

DEV-942 Change “Description” to text field (long text)

---

src/main/java/sg/ncl/ConnectionProperties.java
src/main/java/sg/ncl/DataController.java
src/main/java/sg/ncl/MainController.java
src/main/java/sg/ncl/testbed_interface/DataCategory.java
src/main/java/sg/ncl/testbed_interface/Dataset.java
src/main/resources/messages.properties
src/main/resources/static/js/main.js
src/main/resources/templates/data.html
src/main/resources/templates/data_contribute.html
src/main/resources/templates/data_dashboard.html

1. Add category drop-down
2. Add keywords text input

Cataloguing system

---

src/main/resources/application.properties

Signed-off-by: Tran Ly Vu <vutransingapore@gmail.com>

DEV-987 increase server session time

---

src/main/resources/templates/about.html

Signed-off-by: Tran Ly Vu <vutransingapore@gmail.com>

Update personal page

---

src/main/resources/static/topology-tool/DiagramFigure.js
src/main/resources/static/topology-tool/JSONSerializer.js
src/main/resources/templates/network_diagram.html

Changes: 
1. More user-friendly annotation forms (3 types: node, cloud, port)
1. ESC key closes annotation form
1. Hardcoded number of ports for icons (default is 8)
1. Add collapsible category panels for icons (2 categories: Physical Devices, Virtual Machines)

DEV-1055 Topology tool: GUI improvements

---

src/main/java/sg/ncl/MainController.java
src/main/resources/templates/node_reservation.html
src/main/resources/templates/usage_statistics.html

ADMIN -> Nodes Reservation: sort teams by name
ADMIN -> Team Usage: sort teams by name

Dev 1083 minor enhancements

---

build.gradle
src/main/java/sg/ncl/ConnectionProperties.java
src/main/java/sg/ncl/MainController.java
src/main/java/sg/ncl/domain/ExceptionState.java
src/main/java/sg/ncl/testbed_interface/NodeUsageReservationForm.java
src/main/resources/messages.properties
src/main/resources/static/js/main.js
src/main/resources/templates/about.html
src/main/resources/templates/admin_node_usage_reservation.html
src/main/resources/templates/calendar.html
src/main/resources/templates/edit_page_node_usage_reservation.html
src/main/resources/templates/fragments/dashboard_navigation.html
src/main/resources/templates/plan.html
src/main/resources/templates/testbed_nodes_status.html
src/test/java/sg/ncl/MainControllerTest.java

This task is in reference to proposed changes as part of development of Enhanced Resource Management System
a) change the module name from MONTHLY USAGE to USAGE MANAGEMENT
b) allow users to make reservation via NCL web portal.

Enhanced Resource Management System

---

src/main/java/sg/ncl/ConnectionProperties.java
src/main/java/sg/ncl/MainController.java
src/main/resources/messages.properties
src/main/resources/templates/admin3.html
src/main/resources/templates/admin_data_resources.html
src/main/resources/templates/admin_data_resources_update.html
src/main/resources/templates/admin_monthly.html
src/main/resources/templates/admin_monthly_contribute.html
src/main/resources/templates/admin_monthly_usage.html
src/main/resources/templates/admin_monthly_usage_contribute.html
src/main/resources/templates/admin_node_usage_reservation.html
src/main/resources/templates/admin_usage_analysis.html
src/main/resources/templates/admin_usage_statistics.html
src/main/resources/templates/dashboard.html
src/main/resources/templates/data_dashboard.html
src/main/resources/templates/data_statistics.html
src/main/resources/templates/diskspace_usage.html
src/main/resources/templates/energy_usage.html
src/main/resources/templates/experiment_dashboard.html
src/main/resources/templates/fragments/dashboard_navigation.html
src/main/resources/templates/gpu_dashboard.html
src/main/resources/templates/node_reservation.html
src/main/resources/templates/node_status.html
src/main/resources/templates/team_dashboard.html
src/main/resources/templates/usage_statistics.html
src/main/resources/templates/user_dashboard.html

Read disk usage information from {{/mnt/production_logs/diskspace.txt}} to do the following:
- Display in Admin tab the full list of disk usage of the day
- Display warning/danger alert to users whose disk usage has exceeded the disk usage thresholds
- Scheduled email notification to {{support@ncs.sg}} daily the users whose disk usages has exceeded the thresholds

[Dev-1136] Add Disk Usage Check/Notification Functionality

---

src/main/java/sg/ncl/MainController.java
src/main/resources/templates/testbed_nodes_status.html

Also fix the condition to display the diskspace modal during exception case.

Merge Free and Reserved Nodes stats

---

src/main/resources/templates/fragments/dashboard_navigation.html

For the pentesting exercise in staging environment only

Remove the link 'SWITCH TO OPENSTACK'

---

src/main/java/sg/ncl/testbed_interface/SignUpMergedForm.java

To prevent shell command injection

Validate signup form for special characters

---

src/main/java/sg/ncl/testbed_interface/TeamPageApplyTeamForm.java

Updated message to be displayed

Updated message to be displayed

---

src/main/java/sg/ncl/AesEncryptDecrypt.java
src/main/java/sg/ncl/MainController.java
src/main/java/sg/ncl/TeamManager2.java
src/main/java/sg/ncl/testbed_interface/Team2.java
src/main/resources/templates/teams.html

Fix for NCL-MED-02 – Broken Object Level Authorisation
resolved for the issues mentioned in web-service.
[Service-Web] View Team Profile Feature
(http://dev.ncl.sg/team_profile/\{teamId})
[Service-Web] Join Application Submitted Page
(http://dev.ncl.sg/teams/join_application_submitted/\{teamName})

Fix for dev-1196 NCL-MED-02 – Broken Object Level Authorisation

---

src/main/java/sg/ncl/ConnectionProperties.java
src/main/java/sg/ncl/MainController.java
src/main/java/sg/ncl/TeamManager2.java
src/main/resources/messages.properties
src/main/resources/templates/admin_node_usage_reservation.html
src/main/resources/templates/edit_page_node_usage_reservation.html
src/main/resources/templates/fragments/dashboard_navigation.html
src/main/resources/templates/fragments/login_navigation.html

Changes for Online nodes booking system. 
1.Users can book nodes for their projects.
2.admin can also book nodes on behalf of the users through this feature.
3.admin can view the booking status.

Dev 1207 online nodes reservation/booking for all users.

---

src/main/java/sg/ncl/MainController.java
src/main/resources/templates/fragments/dashboard_navigation.html
src/main/resources/templates/user_monthly.html
src/main/resources/templates/user_monthly_usage.html

Online accounting system rolled out for all users.

DEV-1209 Online accounting system feature for all users

---

src/main/java/sg/ncl/MainController.java

added comment in MainController.java

DEV 1197 - added comment

---

src/main/resources/templates/people.html

DEV-1210 Cleaned code

---

src/main/resources/templates/ncl_publications.html

Updated title on the publications page

Updated title on the publications page

---

build.gradle
src/main/resources/templates/signup2.html

Added reCaptcha to prevent automatic submission of registration form.

DEV-1218 Added reCaptcha to the Registration Form 

---

src/main/java/sg/ncl/MainController.java
src/main/resources/static/css/main.css
src/main/resources/static/js/main.js
src/main/resources/templates/people.html
src/main/resources/templates/recent_events.html
src/main/resources/templates/services_and_tools1.html
src/main/resources/templates/testbed_information.html
src/test/java/sg/ncl/MainControllerTest.java

This PR includes:
DEV-1251: Consist of changes regarding implementation of editing static content of People.html and RecentEvent.html dynamically from the website. Code changes include adding two javascript methods which will fetch information from github and publish it on ncl.sg. Repos holding static content is : "static-web-content".
DEV-1249: Consist of changing email-id from dscacr@nus.edu.sg to support@ncl.edu.sg, some layout changes, and background color of the topic heading in people.html.
DEV-1245: This change is to fix issue regarding NCL User’s unable to access the running nodes of their experiments through SSH and VNC. It shows a broken link. The problem recognized due to "." in the URL.

[DEV-1250] Website Updates - December 2021

---

src/main/java/sg/ncl/MainController.java
src/main/resources/static/js/main.js
src/main/resources/templates/event.html
src/main/resources/templates/pricing.html
src/main/resources/templates/recent_events.html
src/main/resources/templates/testbed_information.html

This PR consist of following changes :
- Converting testbed information page to content editable.
- Converting pricing page to content editable.
- Changing layout to recent events page.
- Moving two events from recent events to past events.

1269- Converting web pages to static content editable.

---

src/main/java/sg/ncl/MainController.java
src/main/java/sg/ncl/testbed_interface/InstanceInfo.java
src/main/java/sg/ncl/testbed_interface/OpenStackServerStateful.java
src/main/resources/templates/experiment_profile.html
src/main/resources/templates/tutorials.html

-[DEV-1270] Change OpenStack Instance Info Format Style. - Duplicate ticket.
-Updated on the Realization page format Style.

[DEV-1267]Change OpenStack Instance Info Format Style.

---

Dockerfile
docker-compose.yml

In order to make it easier for delivery and deployment.

[DEV-429] Dockerize Web Service

---

src/main/java/sg/ncl/DataController.java
src/main/java/sg/ncl/MainController.java
src/main/resources/templates/about.html
src/main/resources/templates/calendar.html
src/main/resources/templates/community.html
src/main/resources/templates/contactus.html
src/main/resources/templates/email_not_validated.html
src/main/resources/templates/fragments/footer.html
src/main/resources/templates/join_team_application_awaiting_approval.html
src/main/resources/templates/team_application_under_review.html
src/main/resources/templates/testbed_information.html
src/main/resources/templates/updates.html

This PR addresses the following bugs:
- Critical | Outdated Software Version | Upgrade jQuery to version 3.6.0
- Critical | Outdated Software Version | (bootstrap.min.js) Upgrade Bootstrap to version 5.1.3
- Critical | Outdated Software Version | (bootstrap.min.css) Upgrade Bootstrap to version 5.1.3
- Medium | Outdated Software Version | Upgrade DataTables.net to version 1.11.5
- Medium | Outdated Software Version | Upgrade JSZip to version 3.9.0
- Medium | Misconfigured HTTP Security Header | Configure the Strict Transport Security header in the response. Configure with the various HTTP security headers
- Low | Insecure iframe configuration | Add the sandbox attribute in iframe.

[DEV-1284] Fixing SoC vulnerabilities and updating ncl new address

---

src/main/java/sg/ncl/ConnectionProperties.java
src/main/java/sg/ncl/MainController.java
src/main/resources/application.properties
src/main/resources/templates/team_page_apply_team.html
src/test/java/sg/ncl/ConnectionPropertiesTest.java

This PR include :
1) Adding new team
2) Adding verify button to check if team name is availaible
3) Approving new team by admin
4) Requesting to join new team
5)Approving new team join request by owner
6)Rejecting new team join request by owner
7) Rejecting new team creation request by admin

[DEV-1286] Committing teams changes to remove DeterLab dependency

---

src/main/java/sg/ncl/ConnectionProperties.java
src/main/java/sg/ncl/MainController.java
src/main/resources/templates/dashboard.html
src/main/resources/templates/signup2.html

Fixing small issues regarding teams changes.

[DEV-1286] Committing teams changes to remove DeterLab dependency #2

---

src/main/java/sg/ncl/ConnectionProperties.java
src/main/java/sg/ncl/MainController.java
src/main/java/sg/ncl/domain/ExceptionState.java
src/main/java/sg/ncl/testbed_interface/SshInfo.java
src/main/java/sg/ncl/testbed_interface/StudentPasswordResetForm.java
src/main/java/sg/ncl/testbed_interface/VerifyEmailInfo.java
src/main/resources/templates/dashboard.html
src/main/resources/templates/email_ssh_verify.html
src/main/resources/templates/fragments/dashboard_navigation.html
src/main/resources/templates/showpubkeys.html
src/main/resources/templates/student_reset_password.html

This PR includes
1) Manually adding student to the class team by team owner.
2) Uploading and deleting ssh key on NCL web.

[DEV-1292] Manual Add User and SSH Key API Interface

---

src/main/java/sg/ncl/MainController.java
src/main/resources/templates/fragments/login_navigation.html
src/main/resources/templates/index.html
src/main/resources/templates/scholarship.html

Static scholarship page

---

src/main/java/sg/ncl/MainController.java
src/main/resources/templates/123412315125.html
src/main/resources/templates/fragments/login_navigation.html

Adding a demo page for the scholarship.

Adding demo scholarship page

---

src/main/resources/templates/account_settings.html

Removing delete account option from admin

Removing delete account option from admin

---

src/main/resources/static/js/main.js
src/main/resources/templates/data_resources.html

- updated in main.js for dev.
- updated data resources page.

[DEV-1370] Moved Data Resource page to Static Web Content.

---

src/main/java/sg/ncl/MainController.java
src/main/resources/templates/dataset.html
src/main/resources/templates/fragments/dashboard_navigation.html
src/main/resources/templates/fragments/login_navigation.html

Adding new page, Dataset to the testbed dropdown which include content about ChatBot Arena

Changes to add new page (Dataset)

---

src/main/resources/templates/features.html
src/main/resources/templates/fragments/login_navigation.html
src/main/resources/templates/index.html

Created new static page - features.txt
Edited features.html to link it with Static-content repo

Edit testbed Features page to link with static-content repository
